In [1]:
import numpy as np

In [4]:
from time import process_time as pt
python_list = [i for i in range(100000)]
start_time = pt();
python_list = [i+5 for i in python_list]
end_time = pt()
print(end_time-start_time)


0.0


Creating Matrix


In [5]:
#matrix of 2 by 4
matrix1 = np.array([[1,2,3,4],[1,2,3,4]])
print(matrix1)

[[1 2 3 4]
 [1 2 3 4]]


In [6]:
matrix2 = np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]])
print(matrix2)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [9]:
matrix3 = np.array([[1,2,3],[1,2,3]],dtype = float)
matrix3

array([[1., 2., 3.],
       [1., 2., 3.]])

In [8]:
#initial placeholders
matrix4 = np.zeros((2,4))
matrix4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
matrix5 = np.full((3,4),5)
matrix5


array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [11]:
#numpy identity matrix
matrix6 = np.eye(4)
matrix6


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
#putting random values in matrix
matrix7 = np.random.random((3,3))
matrix7

array([[0.49362511, 0.2512141 , 0.79349156],
       [0.45591404, 0.7532349 , 0.69502273],
       [0.03743364, 0.18104981, 0.74964702]])

In [14]:
matrix7 = np.random.randint(10,30,(3,3))
matrix7

array([[22, 20, 26],
       [28, 29, 19],
       [11, 17, 11]], dtype=int32)

In [16]:
matrix8 = np.linspace(10,40,5)
matrix8

array([10. , 17.5, 25. , 32.5, 40. ])

In [20]:
matrix9 = np.arange(10,40,10)
matrix9

array([10, 20, 30])

In [22]:
#conversion of list into array 
list1 = [1,2,3,4]
list2 = [6,7,8,9]
array1 =np.array(list1)
array2  =np.array(list2)
print(array1 ,array2)

[1 2 3 4] [6 7 8 9]


In [23]:
matrix10 = np.random.randint(12,50,(3,3))
matrix10

array([[36, 17, 35],
       [28, 13, 15],
       [45, 17, 18]], dtype=int32)

In [27]:
print(matrix10.shape)

(3, 3)


In [28]:
print(matrix10.ndim)

2


In [29]:
print(matrix10.size)

9


In [30]:
print(matrix10.dtype)

int32


In [31]:
matrix10

array([[36, 17, 35],
       [28, 13, 15],
       [45, 17, 18]], dtype=int32)

In [34]:
matrix7

array([[22, 20, 26],
       [28, 29, 19],
       [11, 17, 11]], dtype=int32)

In [35]:
print(matrix10 +matrix7)
print(matrix10 - matrix7)
print(matrix10 * matrix7)
print(matrix10 /matrix7)

[[58 37 61]
 [56 42 34]
 [56 34 29]]
[[ 14  -3   9]
 [  0 -16  -4]
 [ 34   0   7]]
[[792 340 910]
 [784 377 285]
 [495 289 198]]
[[1.63636364 0.85       1.34615385]
 [1.         0.44827586 0.78947368]
 [4.09090909 1.         1.63636364]]


In [37]:
print(np.add(matrix10 ,matrix7))
print(np.subtract(matrix10 , matrix7))
print(np.multiply(matrix10 , matrix7))
print(np.divide(matrix10,matrix7))

[[58 37 61]
 [56 42 34]
 [56 34 29]]
[[ 14  -3   9]
 [  0 -16  -4]
 [ 34   0   7]]
[[792 340 910]
 [784 377 285]
 [495 289 198]]
[[1.63636364 0.85       1.34615385]
 [1.         0.44827586 0.78947368]
 [4.09090909 1.         1.63636364]]


MOST IMP TRANSPOSE OF A MATRIX

In [38]:
matrix7

array([[22, 20, 26],
       [28, 29, 19],
       [11, 17, 11]], dtype=int32)

In [39]:
trans7 = np.transpose(matrix7)
trans7

array([[22, 28, 11],
       [20, 29, 17],
       [26, 19, 11]], dtype=int32)

In [42]:
matrix10

array([[36, 17, 35],
       [28, 13, 15],
       [45, 17, 18]], dtype=int32)

In [41]:
trans10 = matrix10.T
trans10

array([[36, 28, 45],
       [17, 13, 17],
       [35, 15, 18]], dtype=int32)

In [43]:
#reshaping the array
matrix11 = np.random.randint(1,9,(3,6))
matrix11

array([[8, 4, 2, 3, 8, 3],
       [5, 5, 2, 5, 6, 7],
       [2, 2, 7, 6, 4, 1]], dtype=int32)

In [44]:
trans11 = matrix11.T
trans11

array([[8, 5, 2],
       [4, 5, 2],
       [2, 2, 7],
       [3, 5, 6],
       [8, 6, 4],
       [3, 7, 1]], dtype=int32)

In [46]:
#now reshape
matrix12 = matrix11.reshape(2,9)
matrix12

array([[8, 4, 2, 3, 8, 3, 5, 5, 2],
       [5, 6, 7, 2, 2, 7, 6, 4, 1]], dtype=int32)